### PR TITLE
Fix for error preventing authorization because of missing import

### PR DESCRIPTION
**Pull request by ruuk**
Add to summary and description
Version bump

### CODE REVIEW

**Comment by elbowz** [comment]
Ciao ruuk,

Why do you continue to do push request? 
Do you can do directly push, isn't it?

edit:
thank you for the even number version :)

**Comment by ruuk** [comment]
I hadn't added your upstream url yet as I had originally cloned my fork of your repository, so this was easier, since I could just merge it myself. I found my bug just before I went to bed, so I was on a hurry :)
Next time I'll just add your upstream and push it.

**Comment by elbowz** [comment]
How do you prefer...It's only for understand.

Well, I know there are something to do for really merge our code, and remove all duplicates and redundant function...but I thought we could postpone this work, and before understand if the add-on work as we should...

Do you have some tasks or todos?

I'll open two issue for soon :)

**Comment by ruuk** [comment]
One thing I've thought about is the handling of disconnects or connection errors. For instance if the Kodi machine goes into sleep mode, the service needs to recover when it wakes. I don't think there is anything in the code to do that right now.

By the way, I was also thinking that perhaps the best way to handle pushes is for each of us to develop on his own branch and then merge the changes into master when they're ready. That way we can continue to make changes and push them without affecting the main code. This also gives us the ability to share what we're working on before we merge it.

What do you think?

**Comment by elbowz** [comment]
We have just merged and now do you want fork?! ;)

Do me understand...do you want made 1 branch where we'll work togheter.. Or two branches with the same goal?

I never send my machine in sleep mode (hibernation on HD or on ram?).

I don't know if my code stop to work...have you tried it?!

**Comment by ruuk** [comment]
> We have just merged and now do you want fork?! ;)

I'm just talking about branching :)

> Do me understand...do you want made 1 branch where we'll work togheter.. Or two branches with the same goal?

I mean that I make my changes on my own branch, and when I'm ready I merge that into master.
And you make your changes on your own branch, and when you're ready you merge that into master.

That way, no one is working directly on master. Master only gets merges.
If we work directly on master, then we can't push until we are completely done or we may cause problems for each other.

> I never send my machine in sleep mode (hibernation on HD or on ram?).

Neither do I, but other users do. I had a user that did and it would kill my addon. Plus this also applies to other errors with the WebSocket. We don't want errors to be fatal.

> I don't know if my code stop to work...have you tried it?!

I haven't tried it yet, but most likely if you haven't added any code to deal with these situations, it will die on errors and disconnects. It's possible that the WebSocket api handles these situations, but I doubt it.

**Comment by elbowz** [comment]
> I'm just talking about branching :)

It's the same :P

> I mean that I make my changes on my own branch, and when I'm ready I merge that into master.
> And you make your changes on your own branch, and when you're ready you merge that into master.
> 
> That way, no one is working directly on master. Master only gets merges.
> If we work directly on master, then we can't push until we are completely done or we may cause problems for each other.

If we want do the right things, what do you think something like this:  https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

(with only master develop and features branches)

I think it's also too much for this simple project, but it can be useful for me, to understand how to work better on team :)

> Neither do I, but other users do. I had a user that did and it would kill my addon. Plus this also applies to other errors with the WebSocket. We don't want errors to be fatal.
> 
> I haven't tried it yet, but most likely if you haven't added any code to deal with these situations, it will die on errors and disconnects. It's possible that the WebSocket api handles these situations, but I doubt it.

mhhh... has xbmc some trigger for catch the system wake up? In my add-on I have just created a thread for websocket...

**Comment by ruuk** [comment]
> If we want do the right things, what do you think something like this: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
> 
> (with only master develop and features branches)
> 
> I think it's also too much for this simple project, but it can be useful for me, to understand how to work better on team :)

This seems sensible. We could use branches for features and major changes, but still be able to modify master directly for smaller bugfixes  and and other small things even when we are in the middle of unfinished coding in the branch. Plus we would have the benefit of being able to share the progress on our branch if we want to ask each other questions and things like that.

> mhhh... has xbmc some trigger for catch the system wake up? In my add-on I have just created a thread for websocket...

Not until helix:

```
class Monitor(__builtin__.object)

    onDPMSActivated(...)
        onDPMSActivated() --onDPMSActivated method.

        Will be called when energysaving/DPMS gets active

    onDPMSDeactivated(...)
        onDPMSDeactivated() --onDPMSDeactivated method.

        Will be called when energysaving/DPMS is turned off
```

But in any case we can handle disconnects by reconnecting after a delay, because we need to handle disconnects for other reasons as well.

In my code I would [delay, try to reconnect delay longer, try to reconnect] <-- repeat. I started with a delay of 5 seconds and doubled that each time until it was over a minute and then stayed at one minute. This is just an example of how I handled it.

**Comment by elbowz** [comment]
> This seems sensible. We could use branches for features and major changes, but still be able to modify master directly for smaller bugfixes and and other small things even when we are in the middle of unfinished coding in the branch. Plus we would have the benefit of being able to share the progress on our branch if we want to ask each other questions and things like that.

Perfect, I'll create a develop branch. I though that also the "branch for new feature" could be on github (remote), is it right?

I'm very glad to learn new things and work in the team right mode (master, develop and features branches) but... I would like to know the road map of our Pushbullet add-on.

I don't have many new ideas/todos/features to add. You can read my TODOS on XBMC forum thread:
- Answer messages directly on Kodi **(bw, I think it's quite unuseful)**
- Catch others Kodi notifications to send to other devices (for Sync/Mirroring in outbound mode) **(I can't do without the new XBMC features that I have requested)**
- Incoming call on smartphone => Pause or mute playback on Kodi

What do you want do? I do not spoke of fix and merge...

> In my code I would [delay, try to reconnect delay longer, try to reconnect] <-- repeat. I started with a delay of 5 seconds and doubled that each time until it was over a minute and then stayed at one minute. This is just an example of how I handled it.

I have enable the **ping_interval**, It should send a ping each _interval_ and it should prevent the socket dead also if xbmc disconnect. Feel free to try it on develop branch :)

**Comment by ruuk** [comment]
> Perfect, I'll create a develop branch. I though that also the "branch for new feature" could be on github (remote), is it right?

Do you mean like my persistent_last_modified branch?

> I'm very glad to learn new things and work in the team right mode (master, develop and features branches) but... I would like to know the road map of our Pushbullet add-on.
> 
> I don't have many new ideas/todos/features to add. You can read my TODOS on XBMC forum thread:
> 
> Answer messages directly on Kodi (bw, I think it's quite unuseful)
> Catch others Kodi notifications to send to other devices (for Sync/Mirroring in outbound mode) (I can't do without the new XBMC features that I have requested)
> Incoming call on smartphone => Pause or mute playback on Kodi
> What do you want do? I do not spoke of fix and merge...
> Well, while I was working on my addon, I was just focusing on incoming pushes and an interface. I was going to release that and then focus on more outgoing stuff, both event triggered stuff (ex. sending a note push on Kodi start/stop) and in the interface (ex. creating and pushing a note or pushing a file).
> I'd like to eventually do things that will integrate well with ifttt.com (ex. dim lights when a video starts playing). I think some of this deals with stuff you've already been working on, but I haven't really tried much of your stuff yet other than dismissing from device, as I've been busy coding.

For right now I'm just focusing on cleaning up the merge and fixing issues that I find while not changing or breaking what was already there.

Perhaps I will start adding to the TODO list on the README.md.

> I have enable the ping_interval, It should send a ping each interval and it should prevent the socket dead also if xbmc disconnect. Feel free to try it on develop branch :)

I'll see how this works. I haven't yet tested how the addon handles sleep yet. I need to use my daughter's laptop for that and I've been busy fixing the other stuff.

**Comment by elbowz** [comment]
> Do you mean like my persistent_last_modified branch?

Yeah! Perfect as you have done!

> triggered stuff (ex. sending a note push on Kodi start/stop)

Something like this was requested by a XBMC user (schumi), but I don't like...I'm opened to your suggestions. btw, my mirroring just do this...I don't know well how implement this features (push notes) on interface/settings add-on. I think can be less user friendly and complicated.

But when the time is come, We speak about this, if you want :)

> Perhaps I will start adding to the TODO list on the README.md.

Good idea!

> I'll see how this works. I haven't yet tested how the addon handles sleep yet. I need to use my daughter's laptop for that and I've been busy fixing the other stuff.

I have tested this mod only for unexpected disconnection (ethernet plug out)...
For Suspension/Sleep/Hibernation: don't waste the daughter's laptop ;) 
Do you think the users can be help to test?

We could release a beta version (Develop branch)...with a zip or through your repo. And we could save our time and more important your daughter's laptop ;)

**Comment by ruuk** [comment]
> Something like this was requested by a XBMC user (schumi), but I don't like...I'm opened to your suggestions. btw, my mirroring just do this...I don't know well how implement this features (push notes) on interface/settings add-on. I think can be less user friendly and complicated.

Well, we don't want to make it the default, but this can be an advanced option.

> But when the time is come, We speak about this, if you want :)

Yeah, this is something for the future :)

> > I'll see how this works. I haven't yet tested how the addon handles sleep yet. I need to use my daughter's laptop for that and I've been busy fixing the other stuff.
> > I have tested this mod only for unexpected disconnection (ethernet plug out)...
> > For Suspension/Sleep/Hibernation: don't waste the daughter's laptop ;) 
> > Do you think the users can be help to test?
> 
> We could release a beta version (Develop branch)...with a zip or through your repo. And we could save our time and more important your daughter's laptop ;)

I tested both suspend and disconnecting the network. Both caused the service to die. I opened issue #9.

**Pull request merged**
