### PR TITLE
Sync develop and master branch v0.8.32 

### PR DESCRIPTION
**Pull request by elbowz**
This pull request merge the two branch to keep synced develop and master branch.

Over the change that you can see in commits log, I have added the fix for latest issue #29.

I thought to merge in master and publish on Kodi official repository.

Ciao!

### CODE REVIEW

**Comment by elbowz** [comment]
@ruuk I'm going to merge this pull request at the end of week...if you don't leave any comment.

make me know...ciao!

**Comment by ruuk** [comment]
Sorry, I haven't had time to review the changes yet (it's a fairly large PR :) )

It appears in issue #29 that a user is still getting the error with this branch?

**Comment by elbowz** [comment]
sorry for my disturb...

I know the user on issue #29, but I guess he had made a wrong installation...

anyway this release is better of the current one on Kodi repo ;)

I'm also quite tired of this add-on...all ask support, requests, fix...but no one made a donation or pull request.

**Comment by elbowz** [comment]
if you can add this (https://github.com/andrewleech/script.module.pyopenssl) to official Kodi add-on repo the pull request could be reduced...

**Comment by ruuk** [comment]
Just took a look, and unfortunately we can't add this to the Kodi repo as is, and we can't add the script.module.pyopenssl module as they both contain binary files. We need a pure python solution.

**Comment by elbowz** [comment]
mhhh...Ok, i don't have time to search another solution now.

do you think will be better, set add-on as broken? I remember was your idea...

**Comment by ruuk** [comment]
I'm going to mark the add-on as broken for now.

Since we can't push this code to the repo I'm closing the pull request.

**Pull request closed without merging**
