### PR TITLE
Persistent last modified

### PR DESCRIPTION
**Pull request by ruuk**
This sets _last_modified to the latest modified time of active pushes.
This fixes videos playing that were pushed while Kodi was closed. Previously, after Kodi was opened, when a push was received, all pushes not previously dismissed would interrupt each other.

Also added a setting to prevent pushed videos from interrupting playing video.

Ignore the wierd commits. I accidentally added some code while still on the develop branch and had some adventures getting the code merged into this branch :)

Let me know if you see anything wrong here.

### CODE REVIEW

**Comment by elbowz** [comment]
Cool!

I like a lot this features! Very useful!

I seen your code and It seems very good...I thought, we should start to add some comments to code.

One question: If you merge directly in master, what is the meaning of the **develop** branch?

Do you think is it possible release my **disconnection** branch and your in one add-on release?

edit:
Obviously, you can merge yourself your pull request...but I like this workflow (branch => pull-request => merge)!

**Comment by ruuk** [comment]
> I seen your code and It seems very good...I thought, we should start to add some comments to code.

Yeah, that is a good idea. It is something I need to get better at.

> One question: If you merge directly in master, what is the meaning of the develop branch?

Once merged, we can just delete it. It looks like you moved your changes the disconnect branch, so the develop branch is not in use anyway?

> Do you think is it possible release my disconnection branch and your in one add-on release?
> 
> edit:
> Obviously, you can merge yourself your pull request...but I like this workflow (branch => pull-request => merge)!

It's definitely good for checking each others code.

If it's fine with you, I will merge both branches into master, do some testing to make sure there are no obvious issues and then put a new version in my addon repository.

Perhaps after a few days with it in the hands of the users we could then update the official repository?

**Comment by elbowz** [comment]
Only for understand. I thought something like this:
Image of Yaktocat

For what I understand all features branches start and end only in develop branch. Master is used for release...but I can mistake or misunderstand.

For you, what is the meaning of develop branch? Again, for this project is not needed...

**Comment by elbowz** [comment]
> Perhaps after a few days with it in the hands of the users we could then update the official repository?

Whenever you want! ...remember to add your oauth module

**Comment by ruuk** [comment]
> For what I understand all features branches start and end only in develop branch. Master is used for release...but I can mistake or misunderstand.
> For you, what is the meaning of develop branch? Again, for this project is not needed...

My original thinking was that we would skip a develop branch and just merge into master. But we could use the develop branch in the way shown in the graph. It might be nice to get some experience with this common workflow, even if it may not be totally necessary for this project.

> Whenever you want! ...remember to add your oauth module

Already did that a week ago :)

So I propose that I merge 'disconnect' and  'persistent_last_modified' into 'develop', and test for obvious issues, and then put that on my addon repository. Then if all seems well after the users have tried it, we can merge 'develop' into 'master' and update the official repository.

Should I go ahead and do that?

**Comment by elbowz** [comment]
Yes...go ahead!

**Pull request closed without merging**
